export const ADD_TO_FAVORITE = 'ADD_TO_FAVORITE';
export const REMOVE_FROM_FAVORITE = 'REMOVE_FROM_FAVORITE';
export const FAVORITE_LOADING = 'FAVORITE_LOADING';
export const FAVORITE_FAILURE = 'FAVORITE_FAILURE';
