export const FETCH_WEATHER = 'FETCH_WEATHER';
export const FETCH_WEATHER_MORE = 'FETCH_WEATHER_MORE';
export const WEATHER_LOADING = 'WEATHER_LOADING';
export const WEATHER_FAILURE = 'WEATHER_FAILURE';
export const CHANGE_DAY = 'CHANGE_DAY';
